import { Box, Chip, Container, Divider, Paper, Stack, Typography } from '@mui/material';
import { BarChart2, BookOpen, CheckCircle2, Clock, FileText, Lightbulb, TrendingUp } from 'lucide-react';
import { PipelineTracker } from '../components/PipelineTracker';
import { buildSteps } from '../data/pipelineSteps';

export function InsightStoryPage() {
  return (
    <Box sx={{ py: 4 }}>
      <Container maxWidth={false} sx={{ maxWidth: 1600 }}>

        {/* ── Hero ── */}
        <Paper
          elevation={0}
          sx={{
            p: { xs: 3, md: 5 },
            mb: 4,
            borderRadius: 5,
            background: 'linear-gradient(135deg, #0f172a 0%, #1c1917 50%, #7c2d12 100%)',
            color: 'white',
            position: 'relative',
            overflow: 'hidden',
          }}
        >
          <Box sx={{
            position: 'absolute', top: -60, right: -60,
            width: 300, height: 300, borderRadius: '50%',
            background: 'radial-gradient(circle, rgba(249,115,22,0.18) 0%, transparent 70%)',
            pointerEvents: 'none',
          }} />

          <Stack direction="row" spacing={1.5} sx={{ alignItems: 'center', mb: 3 }}>
            <Box sx={{
              width: 48, height: 48, borderRadius: 3,
              background: 'linear-gradient(135deg,#ea580c,#f97316)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
            }}>
              <FileText size={24} color="white" />
            </Box>
            <Box>
              <Chip
                label="Coming in Part 3"
                size="small"
                icon={<Clock size={11} />}
                sx={{ bgcolor: 'rgba(255,255,255,0.12)', color: 'rgba(255,255,255,0.85)', mb: 0.5 }}
              />
              <Typography variant="h3" sx={{ fontWeight: 800, lineHeight: 1, fontSize: { xs: '1.9rem', md: '2.8rem' } }}>
                Insight Story
              </Typography>
            </Box>
          </Stack>

          <Typography variant="h6" sx={{ maxWidth: 640, color: 'rgba(255,255,255,0.75)', fontWeight: 400, lineHeight: 1.7 }}>
            AI-generated narrative summaries that turn NSA anomaly data and sentiment scores into
            decision-ready insight reports for event organisers.
          </Typography>
        </Paper>

        {/* ── Pipeline context ── */}
        <PipelineTracker
          subtitle="Step 4 of 4 — final output stage"
          steps={buildSteps(3)}
          activeColor="#ea580c"
        />

        {/* ── Feature cards ── */}
        <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3, 1fr)' }, gap: 3, mb: 3 }}>
          <FeatureCard
            icon={<BarChart2 size={22} />}
            title="Aggregated Signal Metrics"
            color="#6366f1"
            items={[
              'Total vs valid vs suspicious record counts',
              'Sentiment distribution breakdown',
              'NSA anomaly pattern summary',
            ]}
          />
          <FeatureCard
            icon={<Lightbulb size={22} />}
            title="AI Narrative Generation"
            color="#ea580c"
            items={[
              'Plain-language summary of feedback quality',
              'Highlights main anomaly patterns detected',
              'Identifies dominant sentiment trends',
            ]}
          />
          <FeatureCard
            icon={<TrendingUp size={22} />}
            title="Decision Support Output"
            color="#0891b2"
            items={[
              'Actionable recommendations for organisers',
              'Exportable PDF / JSON report format',
              'Suitable for stakeholder presentation',
            ]}
          />
        </Box>

        {/* ── Placeholder report preview ── */}
        <Paper elevation={0} sx={{ p: { xs: 3, md: 4 }, borderRadius: 5, bgcolor: 'white', border: '1px dashed', borderColor: 'grey.300' }}>
          <Stack direction="row" spacing={2} sx={{ alignItems: 'center', mb: 3 }}>
            <BookOpen size={20} color="#ea580c" />
            <Typography variant="h6" sx={{ fontWeight: 800 }}>Preview — Sample insight report</Typography>
            <Chip label="Placeholder" size="small" sx={{ bgcolor: 'grey.100' }} />
          </Stack>

          <Paper elevation={0} sx={{ p: 3, borderRadius: 4, bgcolor: '#fafafa', border: '1px solid', borderColor: 'grey.200', opacity: 0.75 }}>
            {/* Report header */}
            <Stack direction="row" sx={{ justifyContent: 'space-between', alignItems: 'flex-start', mb: 2 }}>
              <Box>
                <Typography sx={{ fontWeight: 800, fontSize: '1.1rem' }}>Event Feedback Analysis Report</Typography>
                <Typography variant="caption" color="text.secondary">Generated by EventSense AI · Hybrid NSA + Sentiment Pipeline</Typography>
              </Box>
              <Chip label="Sample output" size="small" sx={{ bgcolor: 'rgba(234,88,12,0.1)', color: '#ea580c' }} />
            </Stack>

            <Divider sx={{ mb: 2 }} />

            {/* Metrics row */}
            <Box sx={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 1.5, mb: 2.5 }}>
              {[
                { label: 'Total records', value: '8', color: '#6366f1' },
                { label: 'Valid (NSA)', value: '5', color: '#22c55e' },
                { label: 'Suspicious', value: '3', color: '#ef4444' },
                { label: 'Positive sentiment', value: '80%', color: '#0891b2' },
              ].map((m) => (
                <Paper key={m.label} elevation={0} sx={{ p: 1.5, borderRadius: 3, bgcolor: 'white', border: '1px solid', borderColor: 'grey.200', textAlign: 'center' }}>
                  <Typography sx={{ fontWeight: 900, fontSize: '1.4rem', color: m.color, lineHeight: 1 }}>{m.value}</Typography>
                  <Typography variant="caption" color="text.secondary">{m.label}</Typography>
                </Paper>
              ))}
            </Box>

            {/* Narrative body */}
            <Box sx={{ p: 2.5, borderRadius: 3, bgcolor: 'white', border: '1px solid', borderColor: 'grey.200' }}>
              <Typography variant="body2" sx={{ lineHeight: 1.9, color: 'text.secondary' }}>
                <strong style={{ color: '#111827' }}>Summary:</strong> Analysis of 8 feedback records identified{' '}
                <strong style={{ color: '#ef4444' }}>3 suspicious entries</strong> via the Negative Selection Algorithm, primarily
                exhibiting spam-like keyword patterns and gibberish token sequences. The remaining{' '}
                <strong style={{ color: '#22c55e' }}>5 valid records</strong> were submitted to sentiment classification.
                <br /><br />
                <strong style={{ color: '#111827' }}>Sentiment overview:</strong> Of the valid records, the majority expressed{' '}
                <strong style={{ color: '#22c55e' }}>positive sentiment</strong> towards the event's organisation, speaker quality,
                and venue. One record registered as neutral, noting a late start while acknowledging content quality.
                <br /><br />
                <strong style={{ color: '#111827' }}>Recommendation:</strong> The high anomaly rate (37.5%) suggests the feedback
                collection channel may benefit from CAPTCHA or rate-limiting controls. Valid feedback signals indicate overall
                positive event reception.
              </Typography>
            </Box>
          </Paper>
        </Paper>

      </Container>
    </Box>
  );
}

// ---------------------------------------------------------------------------
// Sub-component
// ---------------------------------------------------------------------------

function FeatureCard({ icon, title, color, items }: { icon: React.ReactNode; title: string; color: string; items: string[] }) {
  return (
    <Paper elevation={0} sx={{ p: 3, borderRadius: 4, bgcolor: 'white', border: '1px solid', borderColor: 'grey.200' }}>
      <Box sx={{ width: 44, height: 44, borderRadius: 3, bgcolor: `${color}18`, display: 'flex', alignItems: 'center', justifyContent: 'center', mb: 2, color }}>
        {icon}
      </Box>
      <Typography sx={{ fontWeight: 700, mb: 1.5 }}>{title}</Typography>
      <Divider sx={{ mb: 1.5 }} />
      <Stack spacing={1}>
        {items.map((item) => (
          <Stack key={item} direction="row" spacing={1} sx={{ alignItems: 'flex-start' }}>
            <CheckCircle2 size={14} color={color} style={{ marginTop: 2, flexShrink: 0 }} />
            <Typography variant="body2" color="text.secondary">{item}</Typography>
          </Stack>
        ))}
      </Stack>
    </Paper>
  );
}
